//! Species identity and the seed property registry.
//!
//! Canonical identity is the InChIKey (PLAN.md, L1); until the Indigo FFI
//! lands, entries carry their InChIKey as data and are looked up by a short
//! human key. Property values are individual published constants with the
//! source recorded per entry (atomic weights: IUPAC/CIAAW; heat capacities:
//! CODATA/standard reference values in the open literature).

use serde::{Deserialize, Serialize};

use crate::units::{Grams, Liters, Moles};

/// Stable species identifier. Currently a registry key; becomes the InChIKey
/// once L1 identity is wired through Indigo.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(transparent)]
pub struct SpeciesId(pub String);

impl SpeciesId {
    pub fn new(key: &str) -> Self {
        SpeciesId(key.to_string())
    }
}

impl std::fmt::Display for SpeciesId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

/// A curated colour: sRGB plus how strongly it tints a solution.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct Colour {
    pub r: u8,
    pub g: u8,
    pub b: u8,
    /// Tinting strength, roughly "absorbance per mol/L through 1 cm".
    /// Permanganate is enormous (you can see 10⁻⁵ M); copper sulfate is
    /// mild (you need tenths of a mol).
    pub strength: f64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Phase {
    Solid,
    Liquid,
    Aqueous,
    Gas,
}

/// Registry entry for one species.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SpeciesData {
    pub key: &'static str,
    pub name: &'static str,
    pub formula: &'static str,
    pub inchikey: &'static str,
    /// g/mol
    pub molar_mass: f64,
    /// Molar heat capacity of the phase it is added as, J/(mol·K).
    pub heat_capacity: f64,
    /// Density of the pure substance at ~25 °C, g/mL (used for volume of
    /// liquids; approximate, additive-volume assumption is surfaced to the
    /// renderer as such).
    pub density: f64,
    /// Phase the pure substance is in at room conditions.
    pub standard_phase: Phase,
    /// Colour word for observations ("white", "colourless", …), if curated.
    pub appearance: Option<&'static str>,
    /// The colour this substance gives a flame, where it has a
    /// characteristic one. Curated: atomic emission is spectroscopy, not
    /// something the thermodynamic data knows.
    #[serde(default)]
    pub flame_colour: Option<&'static str>,
    /// Reflective colour: what a powder or lump *looks* like. This is
    /// scattering, not transmission, so it stays a plain sRGB value.
    #[serde(default)]
    pub colour: Option<Colour>,
    /// Absorption spectrum of the dissolved species, ε(λ) in
    /// L·mol⁻¹·cm⁻¹ across `spectrum::BAND_NM`. Where a species has one,
    /// solution colour is computed from Beer–Lambert and the CIE observer
    /// rather than tinted — so mixtures compose, concentration changes
    /// hue, and path length matters.
    #[serde(skip, default)]
    pub spectrum: Option<fn() -> crate::spectrum::Spectrum>,
    /// Enthalpy of dissolution in water, kJ/mol, positive = endothermic.
    /// Feeds the vessel energy balance: dissolving NaOH warms the beaker,
    /// dissolving ammonium nitrate would cool it. `None` = not curated yet
    /// (no heat effect is applied, honestly).
    pub dissolution_enthalpy_kj: Option<f64>,
    /// One-line provenance for the constants above.
    /// A salt that goes into solution but whose solution chemistry no
    /// wired engine models.
    ///
    /// Sodium thiosulfate is in no PHREEQC database we ship, so the aqueous
    /// engine cannot speciate it — but it is freely soluble, and leaving it
    /// sitting at the bottom of the beaker as a white solid is a *visibly*
    /// wrong observation about one of the commonest rate practicals. This
    /// flag says: it dissolves, and that is all we claim. No speciation, no
    /// contribution to pH or ionic strength, and the lab says so.
    #[serde(default)]
    pub dissolves_without_speciation: bool,
    /// Some solids are the *stable* phase and still do not appear on a
    /// bench, because the metastable one nucleates first and then sits
    /// there — Ostwald's rule of stages. Copper(II) hydroxide is the
    /// classic case: tenorite (CuO) is more stable by ~1.0 log unit, yet
    /// adding lye to copper sulfate gives the pale blue hydroxide gel, and
    /// it is *heating* that turns it black.
    ///
    /// A Gibbs-minimising engine cannot discover that, because it is a
    /// statement about rates. So it is recorded here as data with its own
    /// provenance rather than special-cased in a solver: below this
    /// temperature the phase is not offered, and above it the engine is
    /// free to find it. `None` means no kinetic barrier is claimed.
    #[serde(default)]
    pub forms_only_above_k: Option<f64>,
    pub provenance: &'static str,
}

impl SpeciesData {
    pub fn moles_from_grams(&self, g: Grams) -> Moles {
        Moles(g.0 / self.molar_mass)
    }

    pub fn grams_from_moles(&self, n: Moles) -> Grams {
        Grams(n.0 * self.molar_mass)
    }

    pub fn liters_from_moles(&self, n: Moles) -> Liters {
        // g / (g/mL) = mL
        Liters(self.grams_from_moles(n).0 / self.density / 1000.0)
    }

    pub fn moles_from_liters(&self, v: Liters) -> Moles {
        self.moles_from_grams(Grams(v.0 * 1000.0 * self.density))
    }
}

/// Seed registry. Grows into the PubChem/Wikidata build-time export (L1).
///
/// Dissolved ions carry `heat_capacity: 0.0`: partial molar heat capacities
/// of aqueous ions are small (often negative) and are not modelled at this
/// stage — the solution's heat capacity is carried by its water. Ion
/// densities are unused (solution volume is carried by the liquid phase).
pub const REGISTRY: &[SpeciesData] = &[
    SpeciesData {
        key: "water",
        name: "water",
        formula: "H2O",
        inchikey: "XLYOFNOQVPJJNP-UHFFFAOYSA-N",
        molar_mass: 18.015,
        heat_capacity: 75.3,
        density: 0.997,
        standard_phase: Phase::Liquid,
        appearance: Some("colourless"),
        flame_colour: None,
        colour: Some(Colour { r: 255, g: 255, b: 255, strength: 0.0 }),
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(l), density: CODATA/standard reference values",
    },
    SpeciesData {
        key: "ethanol",
        name: "ethanol",
        formula: "C2H5OH",
        inchikey: "LFQSCWFLJHTTHZ-UHFFFAOYSA-N",
        molar_mass: 46.069,
        heat_capacity: 112.3,
        density: 0.789,
        standard_phase: Phase::Liquid,
        appearance: Some("colourless"),
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(l), density: standard reference values",
    },
    SpeciesData {
        key: "NaCl",
        name: "sodium chloride",
        formula: "NaCl",
        inchikey: "FAPWRFPIFSIZLT-UHFFFAOYSA-M",
        molar_mass: 58.443,
        heat_capacity: 50.5,
        density: 2.17,
        standard_phase: Phase::Solid,
        appearance: Some("white"),
        flame_colour: Some("bright yellow"),
        colour: Some(Colour { r: 250, g: 250, b: 250, strength: 0.0 }),
        spectrum: None,
        dissolution_enthalpy_kj: Some(3.88),
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(s), density: standard reference values",
    },
    SpeciesData {
        key: "AgNO3",
        name: "silver nitrate",
        formula: "AgNO3",
        inchikey: "SQGYOTSLMSWVJD-UHFFFAOYSA-N",
        molar_mass: 169.87,
        heat_capacity: 93.1,
        density: 4.35,
        standard_phase: Phase::Solid,
        appearance: Some("white"),
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: Some(22.6),
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(s), density: standard reference values",
    },
    SpeciesData {
        key: "AgCl",
        name: "silver chloride",
        formula: "AgCl",
        inchikey: "HKZLPVFGJNLROG-UHFFFAOYSA-M",
        molar_mass: 143.32,
        heat_capacity: 50.8,
        density: 5.56,
        standard_phase: Phase::Solid,
        appearance: Some("white"),
        flame_colour: None,
        colour: Some(Colour { r: 248, g: 248, b: 246, strength: 0.0 }),
        spectrum: None,
        dissolution_enthalpy_kj: Some(65.7),
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(s), density: standard reference values",
    },
    SpeciesData {
        key: "H2O2",
        name: "hydrogen peroxide",
        formula: "H2O2",
        inchikey: "MHAJPDPJQMAIIY-UHFFFAOYSA-N",
        molar_mass: 34.01,
        heat_capacity: 89.1,
        density: 1.11,
        standard_phase: Phase::Liquid,
        appearance: Some("colourless"),
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(l), density: standard reference values. Absent from every shipped PHREEQC database, so it has a decomposition rate but no equilibrium speciation",
    },
    SpeciesData {
        key: "catalase",
        name: "catalase",
        formula: "C",
        inchikey: "",
        molar_mass: 240000.0,
        heat_capacity: 0.0,
        density: 1.3,
        standard_phase: Phase::Aqueous,
        appearance: Some("colourless"),
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: true,
        forms_only_above_k: None,
        provenance: "An enzyme, present only as a catalyst. Its formula is a placeholder — a protein is not a stoichiometric species here and never takes part in a mass balance; only its effect on the activation energy is modelled. Molar mass ~240 kDa (bovine liver catalase, standard reference)",
    },
    SpeciesData {
        key: "MnO2",
        name: "manganese dioxide",
        formula: "MnO2",
        inchikey: "NUJOXMJBOLGQSY-UHFFFAOYSA-N",
        molar_mass: 86.94,
        heat_capacity: 54.1,
        density: 5.03,
        standard_phase: Phase::Solid,
        appearance: Some("black"),
        flame_colour: None,
        colour: Some(Colour { r: 30, g: 28, b: 27, strength: 0.0 }),
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(s), density: standard reference values",
    },
    SpeciesData {
        key: "Na2SO3",
        name: "sodium sulfite",
        formula: "Na2SO3",
        inchikey: "GEHJYWRUCIMESM-UHFFFAOYSA-L",
        molar_mass: 126.04,
        heat_capacity: 120.0,
        density: 2.63,
        standard_phase: Phase::Solid,
        appearance: Some("white"),
        flame_colour: Some("bright yellow"),
        colour: Some(Colour { r: 247, g: 247, b: 245, strength: 0.0 }),
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: true,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(s), density: standard reference values. Like thiosulfate it is absent from every shipped PHREEQC database, so it dissolves without being speciated",
    },
    SpeciesData {
        key: "Na2S2O3",
        name: "sodium thiosulfate",
        formula: "Na2S2O3",
        inchikey: "AKHNMLFCWUSKQB-UHFFFAOYSA-L",
        molar_mass: 158.11,
        heat_capacity: 145.0,
        density: 1.67,
        standard_phase: Phase::Solid,
        appearance: Some("white"),
        flame_colour: Some("bright yellow"),
        colour: Some(Colour { r: 247, g: 247, b: 245, strength: 0.0 }),
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: true,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(s), density: standard reference values. Thiosulfate is absent from every shipped PHREEQC database, so this substance has a rate but no equilibrium speciation, and the lab says so",
    },
    SpeciesData {
        key: "S",
        name: "sulfur",
        formula: "S",
        inchikey: "NINIDFKCEFEMDL-UHFFFAOYSA-N",
        molar_mass: 32.06,
        heat_capacity: 22.6,
        density: 2.07,
        standard_phase: Phase::Solid,
        appearance: Some("pale yellow"),
        flame_colour: None,
        colour: Some(Colour { r: 236, g: 219, b: 96, strength: 0.0 }),
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(s), density: standard reference values for alpha-sulfur",
    },
    SpeciesData {
        key: "SO2",
        name: "sulfur dioxide",
        formula: "SO2",
        inchikey: "RAHZWNYVWXNFOC-UHFFFAOYSA-N",
        molar_mass: 64.07,
        heat_capacity: 39.9,
        density: 0.00293,
        standard_phase: Phase::Gas,
        appearance: Some("colourless"),
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(g), density at STP: standard reference values",
    },
    SpeciesData {
        key: "Ca(OH)2",
        name: "slaked lime (calcium hydroxide)",
        formula: "CaH2O2",
        inchikey: "AXCZMVOFGPJBDE-UHFFFAOYSA-L",
        molar_mass: 74.09,
        heat_capacity: 87.5,
        density: 2.21,
        standard_phase: Phase::Solid,
        appearance: Some("white"),
        flame_colour: Some("brick red"),
        colour: Some(Colour { r: 246, g: 246, b: 244, strength: 0.0 }),
        spectrum: None,
        dissolution_enthalpy_kj: Some(-16.7),
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(s), density, enthalpy of solution: standard reference values. Solubility and speciation computed by PHREEQC (Portlandite in wateq4f.dat/minteq.v4.dat)",
    },
    SpeciesData {
        key: "Cu(OH)2",
        name: "copper(II) hydroxide",
        formula: "CuH2O2",
        inchikey: "PTTPXKJBFFKCEK-UHFFFAOYSA-N",
        molar_mass: 97.56,
        heat_capacity: 96.0,
        density: 3.37,
        standard_phase: Phase::Solid,
        appearance: Some("pale blue"),
        flame_colour: None,
        colour: Some(Colour { r: 137, g: 199, b: 214, strength: 0.0 }),
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(s), density: standard reference values. Colour: the pale blue gelatinous precipitate of the classic school demonstration",
    },
    SpeciesData {
        key: "CuO",
        name: "copper(II) oxide",
        formula: "CuO",
        inchikey: "QPLDLSVMHZLSFG-UHFFFAOYSA-N",
        molar_mass: 79.55,
        heat_capacity: 42.3,
        density: 6.32,
        standard_phase: Phase::Solid,
        appearance: Some("black"),
        flame_colour: None,
        colour: Some(Colour { r: 26, g: 22, b: 20, strength: 0.0 }),
        spectrum: None,
        dissolution_enthalpy_kj: None,
        // Tenorite is the thermodynamically stable copper(II) solid in
        // water - by 1.03 log units against Cu(OH)2 in minteq.v4 - and it
        // is still not what a beaker gives you at room temperature. The
        // hydroxide nucleates first and persists; boiling the suspension
        // is what turns it black, which is the demonstration. 340 K is the
        // temperature at which that conversion becomes brisk enough to
        // watch, and it is an editorial reading of a qualitative
        // observation rather than a measured rate constant.
        dissolves_without_speciation: false,
        forms_only_above_k: Some(340.0),
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(s), density: standard reference values. log_k for Cu(OH)2 (8.674) and Tenorite (7.644) from minteq.v4.dat (USGS/MINTEQA2). The 340 K kinetic threshold is Editorial judgement (Kerotakis): the blue-to-black conversion on warming is qualitative in every source we have, so the number is a stated stand-in for a rate we do not model, not a measurement",
    },
    SpeciesData {
        key: "Na+",
        name: "sodium ion",
        formula: "Na+",
        inchikey: "FKNQFGJONOIPTF-UHFFFAOYSA-N",
        molar_mass: 22.990,
        heat_capacity: 0.0,
        density: 1.0,
        standard_phase: Phase::Aqueous,
        appearance: None,
        flame_colour: Some("bright yellow"),
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; ion Cp not modelled (see module docs)",
    },
    SpeciesData {
        key: "Cl-",
        name: "chloride ion",
        formula: "Cl-",
        inchikey: "VEXZGXHMUGYJMC-UHFFFAOYSA-M",
        molar_mass: 35.453,
        heat_capacity: 0.0,
        density: 1.0,
        standard_phase: Phase::Aqueous,
        appearance: None,
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; ion Cp not modelled (see module docs)",
    },
    SpeciesData {
        key: "Ag+",
        name: "silver ion",
        formula: "Ag+",
        inchikey: "FOIXSVOLVBLSDH-UHFFFAOYSA-N",
        molar_mass: 107.868,
        heat_capacity: 0.0,
        density: 1.0,
        standard_phase: Phase::Aqueous,
        appearance: None,
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; ion Cp not modelled (see module docs)",
    },
    SpeciesData {
        key: "NO3-",
        name: "nitrate ion",
        formula: "NO3-",
        inchikey: "NHNBFGGVMKEFGY-UHFFFAOYSA-N",
        molar_mass: 62.004,
        heat_capacity: 0.0,
        density: 1.0,
        standard_phase: Phase::Aqueous,
        appearance: None,
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; ion Cp not modelled (see module docs)",
    },
    SpeciesData {
        key: "HCl",
        name: "hydrochloric acid",
        formula: "HCl",
        inchikey: "VEXZGXHMUGYJMC-UHFFFAOYSA-N",
        molar_mass: 36.461,
        heat_capacity: 75.3,
        density: 1.19,
        standard_phase: Phase::Liquid,
        appearance: Some("colourless"),
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; modelled as concentrated aqueous acid, dilution heat not curated",
    },
    SpeciesData {
        key: "H2SO4",
        name: "sulfuric acid",
        formula: "H2SO4",
        inchikey: "QAOWNCQODCNURD-UHFFFAOYSA-N",
        molar_mass: 98.079,
        heat_capacity: 75.3,
        density: 1.84,
        standard_phase: Phase::Liquid,
        appearance: Some("colourless, oily"),
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        provenance: "M from IUPAC/CIAAW atomic weights on the same basis as the other sulfates here (S 32.065, O 15.9994); modelled as concentrated aqueous acid, as HCl is. Dilution heat NOT curated, and for this acid that is a real omission rather than a rounding one: diluting concentrated sulfuric acid releases roughly 95 kJ/mol, which is the whole reason for 'add acid to water'. The bench will not warm the beaker, so it cannot teach that lesson yet",
        forms_only_above_k: None,
    },
    SpeciesData {
        key: "NaOH",
        name: "sodium hydroxide",
        formula: "NaOH",
        inchikey: "HEMHJVSKTPXQMS-UHFFFAOYSA-M",
        molar_mass: 39.997,
        heat_capacity: 59.5,
        density: 2.13,
        standard_phase: Phase::Solid,
        appearance: Some("white"),
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: Some(-44.5),
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(s), density, dissolution enthalpy: standard reference values",
    },
    SpeciesData {
        key: "NH3",
        name: "ammonia solution",
        formula: "NH3(aq)",
        inchikey: "QGZKDVFQNNGYKY-UHFFFAOYSA-N",
        molar_mass: 17.031,
        heat_capacity: 80.0,
        density: 0.91,
        standard_phase: Phase::Liquid,
        appearance: Some("colourless, sharp smell"),
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; modelled as household ammonia solution (safety screening only at this stage)",
    },
    SpeciesData {
        key: "NaOCl",
        name: "bleach (sodium hypochlorite)",
        formula: "NaOCl(aq)",
        inchikey: "SUKJFIGYRHOWBL-UHFFFAOYSA-N",
        molar_mass: 74.442,
        heat_capacity: 75.0,
        density: 1.1,
        standard_phase: Phase::Liquid,
        appearance: Some("pale yellow-green"),
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; modelled as household bleach solution (safety screening only at this stage)",
    },
    SpeciesData {
        key: "NH2Cl",
        name: "chloramine",
        formula: "NH2Cl",
        inchikey: "QDHHCQZDFGDHMP-UHFFFAOYSA-N",
        molar_mass: 51.476,
        heat_capacity: 35.0,
        density: 1.0,
        standard_phase: Phase::Gas,
        appearance: Some("sharp-smelling, toxic"),
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; product of the curated bleach+ammonia entry",
    },
    SpeciesData {
        key: "Cl2",
        name: "chlorine gas",
        formula: "Cl2",
        inchikey: "KZBUYRJDOAKODT-UHFFFAOYSA-N",
        molar_mass: 70.906,
        heat_capacity: 33.9,
        density: 1.0,
        standard_phase: Phase::Gas,
        appearance: Some("yellow-green, toxic"),
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(g): standard reference values",
    },
    SpeciesData {
        key: "CH3COOH",
        name: "acetic acid",
        formula: "CH3COOH",
        inchikey: "QTBSBXVTEAMEQO-UHFFFAOYSA-N",
        molar_mass: 60.052,
        heat_capacity: 123.1,
        density: 1.049,
        standard_phase: Phase::Liquid,
        appearance: Some("colourless, vinegar smell"),
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(l), density: standard reference values",
    },
    SpeciesData {
        key: "NaOAc",
        name: "sodium acetate",
        formula: "CH3COONa",
        inchikey: "VMHLLURERBWHNL-UHFFFAOYSA-M",
        molar_mass: 82.034,
        heat_capacity: 79.9,
        density: 1.528,
        standard_phase: Phase::Solid,
        appearance: Some("white"),
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: Some(-17.3),
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(s), density, dissolution enthalpy: standard reference values",
    },
    SpeciesData {
        key: "CH3COO-",
        name: "acetate ion",
        formula: "CH3COO-",
        inchikey: "QTBSBXVTEAMEQO-UHFFFAOYSA-M",
        molar_mass: 59.045,
        heat_capacity: 0.0,
        density: 1.0,
        standard_phase: Phase::Aqueous,
        appearance: None,
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; ion Cp not modelled (see module docs)",
    },
    SpeciesData {
        key: "NaHCO3",
        name: "baking soda (sodium bicarbonate)",
        formula: "NaHCO3",
        inchikey: "UIIMBOGNXHQVGW-UHFFFAOYSA-M",
        molar_mass: 84.007,
        heat_capacity: 87.6,
        density: 2.20,
        standard_phase: Phase::Solid,
        appearance: Some("white"),
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: Some(16.7),
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(s), density, dissolution enthalpy: standard reference values",
    },
    SpeciesData {
        key: "Na2CO3",
        name: "washing soda (sodium carbonate)",
        formula: "Na2CO3",
        inchikey: "CDBYLPFSWZWCQE-UHFFFAOYSA-L",
        molar_mass: 105.988,
        heat_capacity: 112.3,
        density: 2.54,
        standard_phase: Phase::Solid,
        appearance: Some("white"),
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(s), density: standard reference values; dissolution enthalpy not yet curated",
    },
    SpeciesData {
        key: "CO2",
        name: "carbon dioxide",
        formula: "CO2",
        inchikey: "CURLTUGMZLYLDI-UHFFFAOYSA-N",
        molar_mass: 44.009,
        heat_capacity: 37.1,
        density: 1.0,
        standard_phase: Phase::Gas,
        appearance: Some("colourless"),
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(g): standard reference values",
    },
    SpeciesData {
        key: "HCO3-",
        name: "bicarbonate ion",
        formula: "HCO3-",
        inchikey: "BVKZGUZCCUSVTD-UHFFFAOYSA-M",
        molar_mass: 61.017,
        heat_capacity: 0.0,
        density: 1.0,
        standard_phase: Phase::Aqueous,
        appearance: None,
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; ion Cp not modelled (see module docs); books total dissolved carbonate",
    },
    SpeciesData {
        key: "H3PO4",
        name: "phosphoric acid",
        formula: "H3PO4",
        inchikey: "NBIIXXVUZAFLBC-UHFFFAOYSA-N",
        molar_mass: 97.994,
        heat_capacity: 106.1,
        density: 1.88,
        standard_phase: Phase::Liquid,
        appearance: Some("colourless, syrupy"),
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; modelled as the concentrated syrupy acid",
    },
    SpeciesData {
        key: "H2PO4-",
        name: "dihydrogen phosphate ion",
        formula: "H2PO4-",
        inchikey: "NBIIXXVUZAFLBC-UHFFFAOYSA-M",
        molar_mass: 96.987,
        heat_capacity: 0.0,
        density: 1.0,
        standard_phase: Phase::Aqueous,
        appearance: None,
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; ion Cp not modelled (see module docs); books total dissolved phosphate",
    },
    SpeciesData {
        key: "KCl",
        name: "potassium chloride",
        formula: "KCl",
        inchikey: "WCUXLLCKKVVCTQ-UHFFFAOYSA-M",
        molar_mass: 74.551,
        heat_capacity: 51.3,
        density: 1.984,
        standard_phase: Phase::Solid,
        appearance: Some("white"),
        flame_colour: Some("lilac"),
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: Some(17.2),
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(s), density, dissolution enthalpy: standard reference values",
    },
    SpeciesData {
        key: "CaCl2",
        name: "calcium chloride",
        formula: "CaCl2",
        inchikey: "UXVMQQNJUSDDNG-UHFFFAOYSA-L",
        molar_mass: 110.98,
        heat_capacity: 72.9,
        density: 2.15,
        standard_phase: Phase::Solid,
        appearance: Some("white"),
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: Some(-82.8),
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(s), density, dissolution enthalpy (anhydrous): standard reference values",
    },
    SpeciesData {
        key: "CaCO3",
        name: "chalk (calcium carbonate)",
        formula: "CaCO3",
        inchikey: "VTYYLEPIZMXCLO-UHFFFAOYSA-L",
        molar_mass: 100.087,
        heat_capacity: 81.9,
        density: 2.711,
        standard_phase: Phase::Solid,
        appearance: Some("white"),
        flame_colour: None,
        colour: Some(Colour { r: 250, g: 250, b: 248, strength: 0.0 }),
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(s), density (calcite): standard reference values",
    },
    SpeciesData {
        key: "MgSO4",
        name: "magnesium sulfate",
        formula: "MgSO4",
        inchikey: "CSNNHWWHGAXBCP-UHFFFAOYSA-L",
        molar_mass: 120.366,
        heat_capacity: 96.5,
        density: 2.66,
        standard_phase: Phase::Solid,
        appearance: Some("white"),
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(s), density: standard reference values; dissolution enthalpy not curated (hydrate-dependent)",
    },
    SpeciesData {
        key: "gypsum",
        name: "gypsum (calcium sulfate dihydrate)",
        formula: "CaSO4·2H2O",
        inchikey: "PASHVRUKOFIRIK-UHFFFAOYSA-L",
        molar_mass: 172.171,
        heat_capacity: 186.0,
        density: 2.32,
        standard_phase: Phase::Solid,
        appearance: Some("white"),
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(s), density: standard reference values",
    },
    SpeciesData {
        key: "K+",
        name: "potassium ion",
        formula: "K+",
        inchikey: "NPYPAHLBTDXSSS-UHFFFAOYSA-N",
        molar_mass: 39.098,
        heat_capacity: 0.0,
        density: 1.0,
        standard_phase: Phase::Aqueous,
        appearance: None,
        flame_colour: Some("lilac"),
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; ion Cp not modelled (see module docs)",
    },
    SpeciesData {
        key: "Ca+2",
        name: "calcium ion",
        formula: "Ca+2",
        inchikey: "BHPQYMZQTOCNFJ-UHFFFAOYSA-N",
        molar_mass: 40.078,
        heat_capacity: 0.0,
        density: 1.0,
        standard_phase: Phase::Aqueous,
        appearance: None,
        flame_colour: Some("orange-red"),
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; ion Cp not modelled (see module docs)",
    },
    SpeciesData {
        key: "Mg+2",
        name: "magnesium ion",
        formula: "Mg+2",
        inchikey: "JLVVSXFLKOJNIY-UHFFFAOYSA-N",
        molar_mass: 24.305,
        heat_capacity: 0.0,
        density: 1.0,
        standard_phase: Phase::Aqueous,
        appearance: None,
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; ion Cp not modelled (see module docs)",
    },
    SpeciesData {
        key: "Sr+2",
        name: "strontium ion",
        formula: "Sr+2",
        inchikey: "PWYYWQHXAPXYMF-UHFFFAOYSA-N",
        molar_mass: 87.62,
        heat_capacity: 0.0,
        density: 1.0,
        standard_phase: Phase::Aqueous,
        appearance: Some("colourless"),
        flame_colour: Some("crimson red"),
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "identity and InChIKey: PubChem CID 104798 (CC0); M from IUPAC/CIAAW 2021 atomic weights; ion Cp not modelled (see module docs)",
    },
    SpeciesData {
        key: "SO4-2",
        name: "sulfate ion",
        formula: "SO4-2",
        inchikey: "QAOWNCQODCNURD-UHFFFAOYSA-L",
        molar_mass: 96.066,
        heat_capacity: 0.0,
        density: 1.0,
        standard_phase: Phase::Aqueous,
        appearance: None,
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; ion Cp not modelled (see module docs)",
    },
    SpeciesData {
        key: "CaO",
        name: "quicklime (calcium oxide)",
        formula: "CaO",
        inchikey: "ODINCKMPIJJUCX-UHFFFAOYSA-N",
        molar_mass: 56.077,
        heat_capacity: 42.0,
        density: 3.34,
        standard_phase: Phase::Solid,
        appearance: Some("white"),
        flame_colour: None,
        colour: Some(Colour { r: 252, g: 250, b: 245, strength: 0.0 }),
        spectrum: None,
        // KNOWN GAP, stated rather than papered over. Slaking is violently
        // exothermic - CaO + H2O -> Ca(OH)2 releases about 82 kJ/mol, which
        // is why a bucket of quicklime steams and why it is a burn hazard.
        // The bench currently shows the vessel *cooling* instead, because
        // the energy balance only reads Dissolved and Precipitated events
        // and a solid turning into a different solid emits neither. Putting
        // the number here would not fix that; it would just look fixed.
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(s), density: standard reference values. The heat of slaking is NOT modelled: see the note on dissolution_enthalpy_kj",
    },
    SpeciesData {
        key: "Mg",
        name: "magnesium",
        formula: "Mg",
        inchikey: "FYYHWMGAXLPEAU-UHFFFAOYSA-N",
        molar_mass: 24.305,
        heat_capacity: 24.9,
        density: 1.738,
        standard_phase: Phase::Solid,
        appearance: Some("silvery"),
        flame_colour: Some("a blinding white"),
        colour: Some(Colour { r: 200, g: 202, b: 205, strength: 0.0 }),
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(s), density: standard reference values",
    },
    SpeciesData {
        key: "Cu",
        name: "copper",
        formula: "Cu",
        inchikey: "RYGMFSIKBFXOCR-UHFFFAOYSA-N",
        molar_mass: 63.546,
        heat_capacity: 24.44,
        density: 8.96,
        standard_phase: Phase::Solid,
        appearance: Some("reddish-brown"),
        flame_colour: Some("blue-green"),
        colour: Some(Colour { r: 184, g: 115, b: 51, strength: 0.0 }),
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(s), density: standard reference values",
    },
    SpeciesData {
        key: "Zn",
        name: "zinc",
        formula: "Zn",
        inchikey: "HCHKCACWOHOZIP-UHFFFAOYSA-N",
        molar_mass: 65.38,
        heat_capacity: 25.39,
        density: 7.14,
        standard_phase: Phase::Solid,
        appearance: Some("bluish-silver"),
        flame_colour: None,
        colour: Some(Colour { r: 186, g: 196, b: 200, strength: 0.0 }),
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(s), density: standard reference values",
    },
    SpeciesData {
        key: "Ag",
        name: "silver",
        formula: "Ag",
        inchikey: "BQCADISMDOOEFD-UHFFFAOYSA-N",
        molar_mass: 107.868,
        heat_capacity: 25.35,
        density: 10.49,
        standard_phase: Phase::Solid,
        appearance: Some("silvery-white"),
        flame_colour: None,
        colour: Some(Colour { r: 192, g: 192, b: 192, strength: 0.0 }),
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(s), density: standard reference values",
    },
    SpeciesData {
        key: "Fe",
        name: "iron",
        formula: "Fe",
        inchikey: "XEEYBQQBJWHFJM-UHFFFAOYSA-N",
        molar_mass: 55.845,
        heat_capacity: 25.1,
        density: 7.874,
        standard_phase: Phase::Solid,
        appearance: Some("grey"),
        flame_colour: None,
        colour: Some(Colour { r: 120, g: 120, b: 125, strength: 0.0 }),
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(s), density: standard reference values",
    },
    SpeciesData {
        key: "MgO",
        name: "magnesium oxide",
        formula: "MgO",
        inchikey: "CPLXHLVBOLITMK-UHFFFAOYSA-N",
        molar_mass: 40.304,
        heat_capacity: 37.2,
        density: 3.58,
        standard_phase: Phase::Solid,
        appearance: Some("brilliant white"),
        flame_colour: None,
        colour: Some(Colour { r: 255, g: 255, b: 255, strength: 0.0 }),
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(s), density: standard reference values",
    },
    SpeciesData {
        key: "C",
        name: "carbon (charcoal)",
        formula: "C",
        inchikey: "OKTJSMMVPCPJKN-UHFFFAOYSA-N",
        molar_mass: 12.011,
        heat_capacity: 8.5,
        density: 2.26,
        standard_phase: Phase::Solid,
        appearance: Some("black"),
        flame_colour: None,
        colour: Some(Colour { r: 24, g: 24, b: 26, strength: 0.0 }),
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(s, graphite), density: standard reference values",
    },
    SpeciesData {
        key: "O2",
        name: "oxygen",
        formula: "O2",
        inchikey: "MYMOFIZGZYHOMD-UHFFFAOYSA-N",
        molar_mass: 31.998,
        heat_capacity: 29.4,
        density: 1.0,
        standard_phase: Phase::Gas,
        appearance: Some("colourless"),
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(g): standard reference values",
    },
    SpeciesData {
        key: "N2",
        name: "nitrogen",
        formula: "N2",
        inchikey: "IJGRMHOSHXDMSA-UHFFFAOYSA-N",
        molar_mass: 28.014,
        heat_capacity: 29.1,
        density: 1.0,
        standard_phase: Phase::Gas,
        appearance: Some("colourless"),
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(g): standard reference values",
    },
    SpeciesData {
        key: "CuSO4",
        name: "copper sulfate",
        formula: "CuSO4",
        inchikey: "ARUVKPQLZAKDPS-UHFFFAOYSA-L",
        molar_mass: 159.609,
        heat_capacity: 100.0,
        density: 3.60,
        standard_phase: Phase::Solid,
        appearance: Some("white when dry"),
        flame_colour: Some("blue-green"),
        colour: Some(Colour { r: 245, g: 245, b: 240, strength: 0.0 }),
        spectrum: None,
        dissolution_enthalpy_kj: Some(-73.1),
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(s), density, dissolution enthalpy (anhydrous): standard reference values",
    },
    SpeciesData {
        key: "Cu+2",
        name: "copper(II) ion",
        formula: "Cu+2",
        inchikey: "JPVYNHNXODAKFH-UHFFFAOYSA-N",
        molar_mass: 63.546,
        heat_capacity: 0.0,
        density: 1.0,
        standard_phase: Phase::Aqueous,
        appearance: Some("blue"),
        flame_colour: Some("blue-green"),
        colour: Some(Colour { r: 40, g: 110, b: 210, strength: 60.0 }),
        // [Cu(H2O)6]2+ absorbs through a broad, weak d–d band peaking in
        // the near infrared (~810 nm, ε ≈ 12). Only its tail reaches the
        // visible, which is why the solution is *pale* blue and why you
        // need tenths of a mole to see anything at all.
        spectrum: Some(|| crate::spectrum::edge(0.6, 11.0)),
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; colour curated, strength set from the published molar absorptivity of [Cu(H2O)6]2+ (ε ≈ 12 L/mol/cm) over a beaker-sized path",
    },
    SpeciesData {
        key: "KMnO4",
        name: "potassium permanganate",
        formula: "KMnO4",
        inchikey: "VZJVWSHVAAUDKD-UHFFFAOYSA-N",
        molar_mass: 158.034,
        heat_capacity: 119.2,
        density: 2.70,
        standard_phase: Phase::Solid,
        appearance: Some("dark purple crystals"),
        flame_colour: Some("lilac"),
        colour: Some(Colour { r: 60, g: 20, b: 70, strength: 0.0 }),
        spectrum: None,
        dissolution_enthalpy_kj: Some(16.2),
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(s), density, dissolution enthalpy: standard reference values",
    },
    SpeciesData {
        key: "FeSO4",
        name: "iron(II) sulfate",
        formula: "FeSO4",
        inchikey: "BAUYGSIQEAFULO-UHFFFAOYSA-L",
        molar_mass: 151.91,
        heat_capacity: 100.6,
        density: 3.65,
        standard_phase: Phase::Solid,
        appearance: Some("pale green"),
        flame_colour: None,
        colour: Some(Colour { r: 178, g: 196, b: 160, strength: 0.0 }),
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(s), density: standard reference values. The reagent a permanganate titration is standardised against, and the cleanest way to put a reducing agent in the beaker",
    },
    SpeciesData {
        key: "Fe+2",
        name: "iron(II) ion",
        formula: "Fe+2",
        inchikey: "CWYNVVGOOAEACU-UHFFFAOYSA-N",
        molar_mass: 55.845,
        heat_capacity: 0.0,
        density: 1.0,
        standard_phase: Phase::Aqueous,
        appearance: Some("pale green"),
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights. The reduced half of the couple school electrochemistry is built on",
    },
    SpeciesData {
        key: "Fe+3",
        name: "iron(III) ion",
        formula: "Fe+3",
        inchikey: "VTLYFUHAOXGGBS-UHFFFAOYSA-N",
        molar_mass: 55.845,
        heat_capacity: 0.0,
        density: 1.0,
        standard_phase: Phase::Aqueous,
        appearance: Some("pale yellow"),
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights. The oxidised half; whether iron is here or as Fe(II) is what a redox experiment measures",
    },
    SpeciesData {
        key: "Cu+1",
        name: "copper(I) ion",
        formula: "Cu+1",
        inchikey: "VMQMZMRVKUZKQL-UHFFFAOYSA-N",
        molar_mass: 63.546,
        heat_capacity: 0.0,
        density: 1.0,
        standard_phase: Phase::Aqueous,
        appearance: Some("colourless"),
        flame_colour: Some("blue-green"),
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights. Copper(I): unstable in water on its own — it disproportionates — but a real part of the distribution a coupled solve finds, and present here so that copper which settles into it is counted rather than dropped",
    },
    SpeciesData {
        key: "Mn+2",
        name: "manganese(II) ion",
        formula: "Mn+2",
        inchikey: "WAEMQWOKJMHJLA-UHFFFAOYSA-N",
        molar_mass: 54.94,
        heat_capacity: 0.0,
        density: 1.0,
        standard_phase: Phase::Aqueous,
        appearance: Some("very pale pink"),
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights. The reduced manganese the databases book dissolved Mn as; its faint pink is why a permanganate titration endpoint is read on the purple going, not on anything arriving",
    },
    SpeciesData {
        key: "MnO4-2",
        name: "manganate ion",
        formula: "MnO4-2",
        inchikey: "",
        molar_mass: 118.94,
        heat_capacity: 0.0,
        density: 1.0,
        standard_phase: Phase::Aqueous,
        appearance: Some("green"),
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights. Manganese(VI): the deep green intermediate between permanganate and manganese dioxide, and a real minor product of permanganate in alkali — it exists here so that manganese which settles into this state is counted rather than quietly lost",
    },
    SpeciesData {
        key: "Mn+3",
        name: "manganese(III) ion",
        formula: "Mn+3",
        inchikey: "",
        molar_mass: 54.94,
        heat_capacity: 0.0,
        density: 1.0,
        standard_phase: Phase::Aqueous,
        appearance: Some("red"),
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights. Manganese(III), which the databases carry and a coupled solve can land a little of matter in; present so that it is counted",
    },
    SpeciesData {
        key: "MnO4-",
        name: "permanganate ion",
        formula: "MnO4-",
        inchikey: "VLTRZXGMWDSKGL-UHFFFAOYSA-M",
        molar_mass: 118.934,
        heat_capacity: 0.0,
        density: 1.0,
        standard_phase: Phase::Aqueous,
        appearance: Some("intense purple"),
        flame_colour: None,
        colour: Some(Colour { r: 120, g: 10, b: 140, strength: 12000.0 }),
        // MnO4- absorbs by ligand-to-metal charge transfer: an intense
        // band at ~525 nm (ε ≈ 2400) with the characteristic vibrational
        // shoulders either side. Absorbing green is exactly why it looks
        // purple, and the intensity is why it is visible at 1e-5 M — which
        // is what makes it a self-indicating titrant.
        spectrum: Some(|| {
            crate::spectrum::bands(&[
                (525.0, 2400.0, 22.0),
                (546.0, 1900.0, 20.0),
                (505.0, 1500.0, 18.0),
                (567.0, 900.0, 18.0),
            ])
        }),
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; colour curated, strength set from the published molar absorptivity of MnO4- (ε ≈ 2400 L/mol/cm at 525 nm) — visible at 1e-5 M, which is why it is the classic titration indicator",
    },
    SpeciesData {
        key: "phenolphthalein",
        name: "phenolphthalein",
        formula: "C20H14O4",
        inchikey: "KJFMBFZCATUALV-UHFFFAOYSA-N",
        molar_mass: 318.323,
        heat_capacity: 0.0,
        density: 1.3,
        standard_phase: Phase::Aqueous,
        appearance: None,
        flame_colour: None,
        colour: None,
        // Deliberately no fixed spectrum: an indicator has two, and which
        // one you see is the question. `indicator::lookup` supplies the
        // mixture the solution's pH actually calls for.
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: true,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW atomic weights; an acid-base indicator, so its colour is not a property of the substance but of the pH around it — see kerotakis_core::indicator, which carries the pKa and both forms' spectra",
    },
    SpeciesData {
        key: "methyl_orange",
        name: "methyl orange",
        formula: "C14H14N3NaO3S",
        inchikey: "BSKHPKMHTQYZBB-UHFFFAOYSA-N",
        molar_mass: 327.334,
        heat_capacity: 0.0,
        density: 1.3,
        standard_phase: Phase::Aqueous,
        appearance: None,
        flame_colour: None,
        colour: None,
        // Deliberately no fixed spectrum: an indicator has two, and which
        // one you see is the question. `indicator::lookup` supplies the
        // mixture the solution's pH actually calls for.
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: true,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW atomic weights; sodium salt, freely soluble; colour is pH-dependent — see kerotakis_core::indicator",
    },
    SpeciesData {
        key: "bromothymol_blue",
        name: "bromothymol blue",
        formula: "C27H28Br2O5S",
        inchikey: "FBSFWRHWHYMIOG-UHFFFAOYSA-N",
        molar_mass: 624.384,
        heat_capacity: 0.0,
        density: 1.3,
        standard_phase: Phase::Aqueous,
        appearance: None,
        flame_colour: None,
        colour: None,
        // Deliberately no fixed spectrum: an indicator has two, and which
        // one you see is the question. `indicator::lookup` supplies the
        // mixture the solution's pH actually calls for.
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: true,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW atomic weights; colour is pH-dependent — see kerotakis_core::indicator",
    },
    SpeciesData {
        key: "Zn+2",
        name: "zinc ion",
        formula: "Zn+2",
        inchikey: "PTFCDOFLOPIGGS-UHFFFAOYSA-N",
        molar_mass: 65.38,
        heat_capacity: 0.0,
        density: 1.0,
        standard_phase: Phase::Aqueous,
        appearance: Some("colourless"),
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; ion Cp not modelled (see module docs)",
    },
    SpeciesData {
        key: "ZnSO4",
        name: "zinc sulfate",
        formula: "ZnSO4",
        inchikey: "NWONKYPBYAMBJT-UHFFFAOYSA-L",
        molar_mass: 161.47,
        heat_capacity: 99.2,
        density: 3.54,
        standard_phase: Phase::Solid,
        appearance: Some("white"),
        flame_colour: None,
        colour: Some(Colour { r: 245, g: 245, b: 245, strength: 0.0 }),
        spectrum: None,
        dissolution_enthalpy_kj: Some(-80.4),
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(s), density: standard reference values; dissolution enthalpy -80.4 kJ/mol derived from NBS/Wagman 1982 formation enthalpies (ZnSO4(s) -982.8, Zn2+(aq) -153.9, SO4 2-(aq) -909.3 kJ/mol)",
    },
    SpeciesData {
        key: "H2",
        name: "hydrogen",
        formula: "H2",
        inchikey: "UFHFLCQGNIYNRP-UHFFFAOYSA-N",
        molar_mass: 2.016,
        heat_capacity: 28.84,
        density: 1.0,
        standard_phase: Phase::Gas,
        appearance: Some("colourless"),
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(g): standard reference values",
    },
    SpeciesData {
        key: "Pb",
        name: "lead",
        formula: "Pb",
        inchikey: "WABPQHHGFIMREM-UHFFFAOYSA-N",
        molar_mass: 207.2,
        heat_capacity: 26.44,
        density: 11.34,
        standard_phase: Phase::Solid,
        appearance: Some("dull grey"),
        flame_colour: None,
        colour: Some(Colour { r: 120, g: 122, b: 128, strength: 0.0 }),
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; Cp(s), density: standard reference values. NOT flagged as a toxic metal: the L0 screen has no class for that, so lead is as unremarked here as sodium chloride, which is wrong about the world and is written down rather than hidden",
    },
    SpeciesData {
        key: "Pb+2",
        name: "lead(II) ion",
        formula: "Pb+2",
        inchikey: "XMOCLSLCDHWDHP-UHFFFAOYSA-N",
        molar_mass: 207.2,
        heat_capacity: 0.0,
        density: 1.0,
        standard_phase: Phase::Aqueous,
        appearance: Some("colourless"),
        flame_colour: None,
        colour: None,
        spectrum: None,
        dissolution_enthalpy_kj: None,
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; ion Cp not modelled (see module docs)",
    },
    SpeciesData {
        key: "Pb(NO3)2",
        name: "lead(II) nitrate",
        formula: "Pb(NO3)2",
        inchikey: "RLJMLMKIBZAXJO-UHFFFAOYSA-L",
        molar_mass: 331.208,
        heat_capacity: 145.0,
        density: 4.53,
        standard_phase: Phase::Solid,
        appearance: Some("white"),
        flame_colour: None,
        colour: Some(Colour { r: 248, g: 248, b: 248, strength: 0.0 }),
        spectrum: None,
        dissolution_enthalpy_kj: Some(35.4),
        dissolves_without_speciation: false,
        forms_only_above_k: None,
        provenance: "M from IUPAC/CIAAW 2021 atomic weights; density standard reference. Dissolution enthalpy +35.4 kJ/mol derived from NBS/Wagman 1982 formation enthalpies: Pb(NO3)2(s) -451.9, Pb2+(aq) -1.7, NO3-(aq) -207.4 kJ/mol, so -1.7 + 2(-207.4) + 451.9 = +35.4. Calorimetric values around +33.6 are also quoted; the 2 kJ/mol spread is the disagreement between the two routes and is not resolved here. Cp(s) 145 is an ESTIMATE from the nitrates' range, not a sourced value, and nothing computed depends on it while the salt is dissolved",
    },
];

/// The active registry. Currently the static REGISTRY; when the pack
/// loading path is wired (DATA-010), this will return pack-loaded data
/// with the same `&'static` lifetime via `OnceLock` + `Box::leak`.
pub fn registry() -> &'static [SpeciesData] {
    REGISTRY
}

pub fn lookup(id: &SpeciesId) -> Option<&'static SpeciesData> {
    registry().iter().find(|s| s.key == id.0)
}

pub fn lookup_key(key: &str) -> Option<&'static SpeciesData> {
    registry().iter().find(|s| s.key == key)
}
