//! CAP-19: the Python-`thermo` differential oracle (PLAN.md, P3p).
//!
//! Fixtures generated by tools/gen-thermo-fixtures.py — an independent
//! implementation of the same published UNIFAC parameters, plus bubble
//! points solved in Python against the same cited Antoine constants.
//! Disagreement here is our bug, their bug, or genuinely interesting
//! chemistry; it is investigated, never tolerated away. At generation
//! time the two implementations agreed to a part in a million.

use kerotakis_thermo::vle::{ethanol_water_activity, ethanol_water_bubble_point, ETHANOL};

fn fixtures() -> Vec<Vec<String>> {
    let text = include_str!("fixtures/thermo_oracle.tsv");
    text.lines()
        .filter(|l| !l.starts_with('#') && !l.trim().is_empty())
        .map(|l| l.split('\t').map(str::to_string).collect())
        .collect()
}

#[test]
fn unifac_gammas_agree_with_the_independent_implementation() {
    let mut checked = 0;
    for row in fixtures() {
        if row[0] != "gamma" {
            continue;
        }
        let (x, t_k): (f64, f64) = (row[1].parse().unwrap(), row[2].parse().unwrap());
        let (ge_o, gw_o): (f64, f64) = (row[3].parse().unwrap(), row[4].parse().unwrap());
        let (ge, gw) = ethanol_water_activity(x, t_k);
        assert!(
            ((ge - ge_o) / ge_o).abs() < 1e-4,
            "γ_ethanol at x={x}, T={t_k}: ours {ge:.8} vs thermo {ge_o:.8}"
        );
        assert!(
            ((gw - gw_o) / gw_o).abs() < 1e-4,
            "γ_water at x={x}, T={t_k}: ours {gw:.8} vs thermo {gw_o:.8}"
        );
        checked += 1;
    }
    assert!(checked >= 30, "the gamma grid must actually be there");
}

#[test]
fn bubble_points_agree_with_the_independent_solve() {
    let mut checked = 0;
    for row in fixtures() {
        if row[0] != "bubble" {
            continue;
        }
        let (x, p): (f64, f64) = (row[1].parse().unwrap(), row[2].parse().unwrap());
        let (t_o, y_o): (f64, f64) = (row[3].parse().unwrap(), row[4].parse().unwrap());
        let Some(bp) = ethanol_water_bubble_point(x, p) else {
            assert!(
                t_o > ETHANOL.valid_c.1,
                "only an oracle point outside ethanol's fitted range may be refused: x={x}, T={t_o}"
            );
            continue;
        };
        assert!(
            (bp.t_celsius - t_o).abs() < 0.05,
            "bubble T at x={x}: ours {:.4} °C vs oracle {t_o:.4} °C",
            bp.t_celsius
        );
        assert!(
            (bp.y[0] - y_o).abs() < 5e-4,
            "vapour y at x={x}: ours {:.6} vs oracle {y_o:.6}",
            bp.y[0]
        );
        checked += 1;
    }
    assert!(
        checked >= 3,
        "the in-domain bubble subset must actually be there"
    );
}
