//! CAP-19 / tier C: the Python-`thermo` differential oracle (PLAN.md, P3p).
//!
//! Fixtures generated by tools/gen-thermo-fixtures.py — an independent
//! implementation of the same published UNIFAC parameters, plus bubble
//! points solved in Python against the same cited Antoine constants.
//! Disagreement here is our bug, their bug, or genuinely interesting
//! chemistry; it is investigated, never tolerated away.
//!
//! **What each family is independent OF is the whole point and is written
//! down beside it**, in the generator's docstring, in
//! `docs/ORACLE-COVERAGE.md`, and in each test below. `ROADMAP-Webapp.md`
//! states the rule these notes exist to honour: agreement between two
//! paths using the same database is useful but is not an independent
//! validation of that database. Every family here shares the UNIFAC
//! parameter publication with the code it checks, so none of them can say
//! the MODEL is right. What they can say — and this is not small — is that
//! our transcription of ten subgroups and thirty interaction parameters,
//! our combinatorial and residual arithmetic, our finite-difference
//! Gibbs–Helmholtz derivative, our infinite-dilution stand-in and our
//! bubble-point bracketing all agree with a mature independent
//! implementation of the same stated model.

use std::collections::BTreeMap;

use kerotakis_thermo::excess::excess_enthalpy_j_per_mol;
use kerotakis_thermo::lle::infinite_dilution_gamma;
use kerotakis_thermo::unifac::{activity_coefficients, approved_table, GroupDecomposition};
use kerotakis_thermo::vle::{
    bubble_point_with, VapourPressure, ETHANOIC_ACID, ETHANOL, ISOPROPANOL, METHANOL, PROPANONE,
    WATER,
};

/// The UNIFAC decomposition for every name the fixture may use. Kept in
/// step with `COMPONENTS` in the generator by hand and deliberately: a
/// generated copy would drift silently, while a name one side does not
/// know fails here, loudly, with the name in the message.
fn groups(name: &str) -> GroupDecomposition {
    let spec: &[(u32, u32)] = match name {
        "water" => &[(16, 1)],
        "methanol" => &[(15, 1)],
        "ethanol" => &[(1, 1), (2, 1), (14, 1)],
        "propan-2-ol" => &[(1, 2), (3, 1), (14, 1)],
        "propanone" => &[(1, 1), (18, 1)],
        "pentan-3-one" => &[(1, 2), (2, 1), (19, 1)],
        "ethanoic-acid" => &[(1, 1), (42, 1)],
        "hexane" => &[(1, 2), (2, 4)],
        "2-2-dimethylpropane" => &[(1, 4), (4, 1)],
        // `kerotakis-core`'s partition path decomposes methanol this way
        // rather than as the single CH3OH subgroup original UNIFAC assigns
        // it. Pinned so the difference is a number rather than an
        // assumption — see docs/ORACLE-COVERAGE.md.
        "methanol-as-ch3-oh" => &[(1, 1), (14, 1)],
        other => panic!("fixture names a component this test does not know: {other}"),
    };
    let mut g = BTreeMap::new();
    for (id, count) in spec {
        g.insert(*id, *count);
    }
    g
}

/// The curated vapour-pressure correlation for a name, where one exists.
fn vapour_pressure(name: &str) -> VapourPressure {
    match name {
        "water" => WATER,
        "ethanol" => ETHANOL,
        "methanol" => METHANOL,
        "propan-2-ol" => ISOPROPANOL,
        "propanone" => PROPANONE,
        "ethanoic-acid" => ETHANOIC_ACID,
        other => panic!("fixture asks for a bubble point of {other}, which curates no Antoine fit"),
    }
}

fn split_pair(key: &str) -> (&str, &str) {
    key.split_once('+')
        .unwrap_or_else(|| panic!("fixture pair key is not `a+b`: {key}"))
}

fn fixtures() -> Vec<Vec<String>> {
    let text = include_str!("fixtures/thermo_oracle.tsv");
    text.lines()
        .filter(|l| !l.starts_with('#') && !l.trim().is_empty())
        .map(|l| l.split('\t').map(str::to_string).collect())
        .collect()
}

fn rows(family: &str) -> Vec<Vec<String>> {
    fixtures().into_iter().filter(|r| r[0] == family).collect()
}

fn f(row: &[String], i: usize) -> f64 {
    row[i]
        .parse()
        .unwrap_or_else(|_| panic!("column {i} of {row:?} is not a number"))
}

/// Activity coefficients across every binary the approved table can form.
///
/// **Independent of:** our combinatorial and residual arithmetic, our
/// group bookkeeping, and our transcription of the ten subgroup r/q pairs
/// and thirty interaction parameters. The binary list is chosen so that
/// every one of those parameters moves at least one row here; a single
/// mistyped `a_mn` cannot hide.
///
/// **Not independent of:** the parameter publication itself. Both sides
/// read Fredenslund 1975 and Gmehling 1982, so agreement says nothing
/// about whether UNIFAC describes these mixtures.
#[test]
fn unifac_gammas_agree_with_the_independent_implementation() {
    let mut checked = 0;
    let mut pairs = std::collections::BTreeSet::new();
    let table = approved_table();
    for row in rows("gamma") {
        let (a, b) = split_pair(&row[1]);
        let (x, t_k) = (f(&row, 2), f(&row, 3));
        let (ga_o, gb_o) = (f(&row, 4), f(&row, 5));
        let g = activity_coefficients(&table, &[(groups(a), x), (groups(b), 1.0 - x)], t_k);
        assert!(
            ((g[0] - ga_o) / ga_o).abs() < 1e-4,
            "γ({a}) in {a}+{b} at x={x}, T={t_k}: ours {:.8e} vs thermo {ga_o:.8e}",
            g[0]
        );
        assert!(
            ((g[1] - gb_o) / gb_o).abs() < 1e-4,
            "γ({b}) in {a}+{b} at x={x}, T={t_k}: ours {:.8e} vs thermo {gb_o:.8e}",
            g[1]
        );
        pairs.insert(row[1].clone());
        checked += 1;
    }
    eprintln!("gamma: {checked} rows over {} binaries", pairs.len());
    assert!(checked >= 250, "the gamma grid must actually be there");
    assert!(
        pairs.len() >= 17,
        "the grid must span every binary the approved table can form, got {}",
        pairs.len()
    );
}

/// Every parameter in the approved table moves at least one gamma row.
///
/// This is what lets the gamma family be read as a check on the table and
/// not only on the arithmetic. Without it the grid could quietly shrink to
/// one binary again — which is what it was — and the suite would still be
/// green with twenty-four of thirty interaction parameters unexercised.
#[test]
fn the_gamma_grid_reaches_every_curated_parameter() {
    let table = approved_table();
    let mut subgroups: std::collections::BTreeSet<u32> = std::collections::BTreeSet::new();
    let mut mains: std::collections::BTreeSet<u32> = std::collections::BTreeSet::new();
    for row in rows("gamma") {
        let (a, b) = split_pair(&row[1]);
        for name in [a, b] {
            for id in groups(name).keys() {
                subgroups.insert(*id);
                mains.insert(
                    table
                        .group(*id)
                        .unwrap_or_else(|| panic!("subgroup {id} is not in the approved table"))
                        .main_group,
                );
            }
        }
    }
    for group in &table.groups {
        assert!(
            subgroups.contains(&group.id),
            "subgroup {} ({}) has curated r and q that no fixture row can see",
            group.id,
            group.name
        );
    }
    // A parameter is reached when both of its main groups appear in the
    // SAME binary; the per-binary check below is the one that matters.
    let mut reached: std::collections::BTreeSet<(u32, u32)> = std::collections::BTreeSet::new();
    for row in rows("gamma") {
        let (a, b) = split_pair(&row[1]);
        let mut present: std::collections::BTreeSet<u32> = std::collections::BTreeSet::new();
        for name in [a, b] {
            for id in groups(name).keys() {
                present.insert(table.group(*id).unwrap().main_group);
            }
        }
        for m in &present {
            for n in &present {
                if m != n {
                    reached.insert((*m, *n));
                }
            }
        }
    }
    for param in &table.interactions {
        assert!(
            reached.contains(&(param.m, param.n)),
            "interaction a({},{}) = {} is curated but no fixture binary contains both main groups",
            param.m,
            param.n,
            param.a_mn
        );
    }
}

/// Excess enthalpy — the number `kerotakis-core`'s heat-of-mixing
/// equilibrator turns into a temperature change a learner sees.
///
/// **Independent of:** our arithmetic AND our differentiation scheme.
/// `excess.rs` takes a central difference in T with ΔT = 1 K and asserts
/// in a comment that the truncation error is "far below the model's own
/// honesty bound"; thermo differentiates the same model analytically, so
/// this family measures that claim instead of repeating it.
///
/// **Not independent of:** the parameters, or of the larger fact that
/// UNIFAC parameters are fitted to VLE and their Gibbs–Helmholtz hᴱ is
/// qualitative. A passing row does not mean the heat is right; it means
/// our hᴱ is the hᴱ this model implies.
///
/// The tolerance is stated in absolute joules as well as relative,
/// because hᴱ crosses zero: a relative band alone is meaningless at the
/// crossing and would silently pass anything there.
///
/// 0.05 J/mol, and the argument for that width rather than another: the
/// worst disagreement over these 85 rows is 0.0061 J/mol, which is what a
/// central difference with ΔT = 1 K actually costs on this model — the
/// band is eight times that, enough to absorb a float-order
/// rearrangement and not enough to absorb a change of ΔT or of method.
/// For scale it is 0.03% of the acetone–water minimum and a thousandth of
/// the 50 J/mol the allowlist test in `excess.rs` treats as "exothermic
/// mid-range", so a row passing here is nowhere near the bench's own
/// resolution. It is set by what the method costs, not by what passes.
#[test]
fn excess_enthalpies_agree_with_the_analytic_derivative() {
    let mut checked = 0;
    let mut worst: f64 = 0.0;
    for row in rows("hmix") {
        let (a, b) = split_pair(&row[1]);
        let (x, t_k, he_o) = (f(&row, 2), f(&row, 3), f(&row, 4));
        let he = excess_enthalpy_j_per_mol(&[(groups(a), x), (groups(b), 1.0 - x)], t_k);
        let gap = (he - he_o).abs();
        worst = worst.max(gap);
        assert!(
            gap < 0.05 || gap / he_o.abs() < 1e-4,
            "hᴱ of {a}+{b} at x={x}, T={t_k}: ours {he:.6} vs thermo {he_o:.6} J/mol"
        );
        checked += 1;
    }
    eprintln!("hmix: {checked} rows, worst gap {worst:.6} J/mol");
    assert!(checked >= 80, "the hᴱ grid must actually be there");
    assert!(
        worst < 0.05,
        "the 1 K central difference costs at most {worst:.4} J/mol here; if this \
         grew, say why in the diff rather than widening the band"
    );
}

/// Infinite-dilution activity coefficients — the quantity whose RATIO
/// between two solvents `bench.rs` turns into a partition coefficient for
/// a separating funnel.
///
/// **Independent of:** our arithmetic, and of our choice of 1e-9 as the
/// stand-in for "infinitely dilute" only in so far as the oracle uses the
/// same stand-in; the generator mirrors the constant deliberately, so a
/// change to it on one side shows up as a fixture disagreement.
///
/// **Not independent of:** the parameters, or of the group decomposition
/// the consumer feeds in. That second one is load-bearing here: the rows
/// for `methanol` and `methanol-as-ch3-oh` are the same substance under
/// two assignments and they do not agree, which is a finding about the
/// consumer rather than about either implementation.
#[test]
fn infinite_dilution_gammas_agree_with_the_independent_implementation() {
    let mut checked = 0;
    for row in rows("gammainf") {
        let (solute, solvent) = (row[1].as_str(), row[2].as_str());
        let (t_k, g_o) = (f(&row, 3), f(&row, 4));
        let g = infinite_dilution_gamma(&groups(solute), &groups(solvent), t_k);
        assert!(
            ((g - g_o) / g_o).abs() < 1e-4,
            "γ∞({solute} in {solvent}) at T={t_k}: ours {g:.8e} vs thermo {g_o:.8e}"
        );
        checked += 1;
    }
    eprintln!("gammainf: {checked} rows");
    assert!(checked >= 12, "the γ∞ grid must actually be there");
}

/// The two methanol decompositions disagree, and by how much is recorded.
///
/// This is not a check that anything is right. It is a pin on a number
/// that a consumer's choice moves, so the choice cannot drift back into
/// being invisible. `bench.rs::partition_groups` builds methanol from CH3
/// and OH; original UNIFAC assigns it the single CH3OH subgroup, which is
/// what `approved_table()`'s own comment says that subgroup is FOR. The
/// partition coefficient the bench reports for methanol between hexane
/// and water depends on which one is used.
#[test]
fn the_two_methanol_assignments_are_pinned_apart() {
    let ratio = |name: &str| {
        infinite_dilution_gamma(&groups(name), &groups("water"), 298.15)
            / infinite_dilution_gamma(&groups(name), &groups("hexane"), 298.15)
    };
    let standard = ratio("methanol");
    let as_used = ratio("methanol-as-ch3-oh");
    let disagreement = (standard - as_used).abs() / standard;
    assert!(
        disagreement > 0.2,
        "the two assignments were {:.1} per cent apart when this was written \
         (0.1070 against 0.0841); if they have converged, the finding in \
         docs/ORACLE-COVERAGE.md is closed and this test should say so",
        100.0 * disagreement
    );
}

/// Bubble points, across every binary curating an Antoine fit on both
/// sides — five, where this family used to cover one.
///
/// **Independent of:** our flash solver, its bracketing and its γ(T)
/// loop. The oracle bisects the same stated model in Python.
///
/// **Not independent of:** the Antoine constants, which the generator
/// duplicates on purpose. NOTHING in this repository checks whether those
/// constants are right; four of the six are unreachable by this oracle
/// because reaching them would mean reading thermo's compound database,
/// which `provenance/upstreams.toml` does not clear. See
/// docs/ORACLE-COVERAGE.md, "what is not reachable".
#[test]
fn bubble_points_agree_with_the_independent_solve() {
    let mut checked = 0;
    let mut refused = 0;
    let mut pairs = std::collections::BTreeSet::new();
    let table = approved_table();
    for row in rows("bubble") {
        let (a, b) = split_pair(&row[1]);
        let (x, p) = (f(&row, 2), f(&row, 3));
        let (t_o, y_o) = (f(&row, 4), f(&row, 5));
        let (va, vb) = (vapour_pressure(a), vapour_pressure(b));
        let answer = bubble_point_with(&[va, vb], &[x, 1.0 - x], p, |t_k| {
            activity_coefficients(&table, &[(groups(a), x), (groups(b), 1.0 - x)], t_k)
        });
        let Some(bp) = answer else {
            // A refusal is only honest if the oracle's own answer is
            // outside a fitted range we declare. Anything else is a
            // solver that gave up inside its own domain.
            let inside = |v: &VapourPressure| {
                v.valid_range()
                    .map(|(lo, hi)| t_o >= lo && t_o <= hi)
                    .unwrap_or(false)
            };
            assert!(
                !(inside(&va) && inside(&vb)),
                "{a}+{b} at x={x} was refused, but the oracle's {t_o:.3} °C is \
                 inside both fitted ranges"
            );
            refused += 1;
            continue;
        };
        assert!(
            (bp.t_celsius - t_o).abs() < 0.05,
            "bubble T of {a}+{b} at x={x}: ours {:.4} °C vs oracle {t_o:.4} °C",
            bp.t_celsius
        );
        assert!(
            (bp.y[0] - y_o).abs() < 5e-4,
            "vapour y({a}) of {a}+{b} at x={x}: ours {:.6} vs oracle {y_o:.6}",
            bp.y[0]
        );
        pairs.insert(row[1].clone());
        checked += 1;
    }
    eprintln!("bubble: {checked} rows compared, {refused} refused as out of range");
    assert!(
        checked >= 12,
        "the in-domain bubble subset must actually be there, got {checked} \
         ({refused} refused)"
    );
    assert!(
        pairs.len() >= 3,
        "more than one binary must reach a bubble point, got {pairs:?}"
    );
}
