//! # kerotakis-codex
//!
//! The curated part: curriculum reactions with the concepts that explain
//! them, written at every register, each carrying its provenance.
//!
//! The codex is TOML because a chemistry editor has to be able to write it
//! without a build step. Its schema is deliberately small — an entry is a
//! *setup script*, the observations it claims, the words for each register,
//! and where the claim comes from.
//!
//! The point of the format is the check it enables. Because a setup is a
//! `.lab` script, `lint` can **replay every entry through the real
//! solvers** and confirm the claimed observations actually occur. A codex
//! entry that stops being true fails the build. Nothing else in this
//! project would catch a curation error; this does.

use kerotakis_core::Register;
use serde::{Deserialize, Serialize};

/// One curated reaction.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Entry {
    /// Stable slug, used by lessons and the concept graph.
    pub id: String,
    /// Balanced equation, shown from the student register up.
    pub equation: String,
    /// Concepts this reaction teaches; the difficulty ladder is built from
    /// these edges.
    #[serde(default)]
    pub concepts: Vec<String>,
    /// Concepts a learner needs first.
    #[serde(default)]
    pub requires: Vec<String>,
    /// Where this sits in a curriculum. Several may apply: the same
    /// reaction is met at different depths in different systems, and the
    /// same system meets it more than once.
    #[serde(default)]
    pub curriculum: Vec<Placement>,
    /// Apparatus the experiment needs, by registry-independent name
    /// ("beaker", "burette", "crucible", "bunsen"). Drives what a UI puts
    /// on the bench and what a real teacher would have to fetch.
    #[serde(default)]
    pub apparatus: Vec<String>,
    /// Calculations a learner is expected to perform here
    /// ("moles-from-mass", "concentration", "titration-stoichiometry",
    /// "percentage-yield", "enthalpy-change").
    #[serde(default)]
    pub calculations: Vec<String>,
    /// Models a learner is expected to reason with ("particle-model",
    /// "ionic-bonding", "collision-theory", "equilibrium", "orbital").
    /// The same reaction is explained by different models at different
    /// levels, which is what makes a level more than a change of wording.
    #[serde(default)]
    pub models: Vec<String>,
    pub setup: Setup,
    pub expect: Expect,
    pub registers: Registers,
    pub provenance: Provenance,
}

/// One curriculum's placement of an entry.
///
/// Kept deliberately loose: a `system` string, a `stage` as that system
/// writes it, and an approximate age band so entries can be compared
/// across systems that number their years differently. The citation is
/// required — a placement claim is a claim about someone's document.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Placement {
    /// e.g. "england-national-curriculum", "australian-curriculum-v9",
    /// "bayern-lehrplanplus", "openstax-chemistry-2e".
    pub system: String,
    /// The stage as that system names it: "KS3", "Year 10", "Jgst. 9",
    /// "Chapter 4.2".
    pub stage: String,
    /// Approximate age band, for cross-system comparison.
    #[serde(default)]
    pub ages: Option<Range>,
    /// Where the placement was read from, and under what licence.
    pub source: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Setup {
    /// A `.lab` script: the same grammar the CLI and the browser run.
    pub script: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Expect {
    /// Events that must occur, as `kind` or `kind:species`, e.g.
    /// `precipitated:AgCl`, `gas_evolved:CO2`, `hazard_warning`.
    #[serde(default)]
    pub events: Vec<String>,
    /// Events that must *not* occur — the guard against a lesson quietly
    /// starting to lie in the other direction.
    #[serde(default)]
    pub absent: Vec<String>,
    /// Optional numeric checks on the final state of a vessel.
    #[serde(default)]
    pub ph: Option<Range>,
    #[serde(default)]
    pub temperature_c: Option<Range>,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct Range {
    pub min: f64,
    pub max: f64,
}

impl Range {
    pub fn contains(&self, v: f64) -> bool {
        v >= self.min && v <= self.max
    }
}

/// The same chemistry at each level of detail, keyed by level number
/// (`lv1`, `lv2`, `lv3`, …). A map rather than named fields so that adding
/// granularity later is a data change, not a schema change. Never
/// generated by a language model: written by a person, checked against the
/// solvers.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(transparent)]
pub struct Registers(pub std::collections::BTreeMap<String, String>);

impl Registers {
    pub fn get(&self, level: u8) -> Option<&str> {
        self.0.get(&format!("lv{level}")).map(String::as_str)
    }

    /// Levels present, ascending.
    pub fn levels(&self) -> Vec<u8> {
        let mut out: Vec<u8> = self
            .0
            .keys()
            .filter_map(|k| k.trim_start_matches("lv").parse().ok())
            .collect();
        out.sort_unstable();
        out
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Provenance {
    /// Where the chemistry claim comes from.
    pub source: String,
    /// Licence of that source, where it is a dataset rather than common
    /// textbook knowledge.
    #[serde(default)]
    pub licence: Option<String>,
    /// What computed the numbers, if any were computed.
    #[serde(default)]
    pub computed_by: Option<String>,
}

#[derive(Debug, Default, Serialize, Deserialize)]
pub struct Codex {
    #[serde(default, rename = "reaction")]
    pub reactions: Vec<Entry>,
}

#[derive(Debug, thiserror::Error)]
pub enum CodexError {
    #[error("could not parse the codex: {0}")]
    Parse(#[from] toml::de::Error),
}

impl Codex {
    pub fn parse(text: &str) -> Result<Codex, CodexError> {
        Ok(toml::from_str(text)?)
    }

    /// Structural problems that need no solver: duplicate ids, empty
    /// registers, missing provenance, dangling prerequisites.
    pub fn structural_problems(&self) -> Vec<String> {
        let mut problems = Vec::new();
        let mut seen: Vec<&str> = Vec::new();
        let taught: Vec<&str> = self
            .reactions
            .iter()
            .flat_map(|r| r.concepts.iter().map(String::as_str))
            .collect();
        for r in &self.reactions {
            if seen.contains(&r.id.as_str()) {
                problems.push(format!("{}: duplicate id", r.id));
            }
            seen.push(&r.id);
            if r.equation.trim().is_empty() {
                problems.push(format!("{}: no equation", r.id));
            }
            if r.setup.script.trim().is_empty() {
                problems.push(format!("{}: no setup script — nothing to verify", r.id));
            }
            if r.expect.events.is_empty() && r.expect.ph.is_none() {
                problems.push(format!(
                    "{}: claims nothing checkable; an entry the solvers cannot verify is a story, not chemistry",
                    r.id
                ));
            }
            // Every entry must speak at the three established levels; more
            // are welcome and need no code change.
            for level in [1u8, 2, 3] {
                match r.registers.get(level) {
                    Some(t) if !t.trim().is_empty() => {}
                    _ => problems.push(format!("{}: nothing written at lv{level}", r.id)),
                }
            }
            for key in r.registers.0.keys() {
                if Register::parse(key).is_none() {
                    problems.push(format!(
                        "{}: register key '{key}' is not a level (use lv1, lv2, …)",
                        r.id
                    ));
                }
            }
            if r.provenance.source.trim().is_empty() {
                problems.push(format!("{}: no provenance", r.id));
            }
            if r.concepts.is_empty() {
                problems.push(format!("{}: teaches no named concept", r.id));
            }
            for p in &r.curriculum {
                if p.source.trim().is_empty() {
                    problems.push(format!(
                        "{}: placement in '{}' cites no source — a placement is a claim about someone's document",
                        r.id, p.system
                    ));
                }
            }
            for need in &r.requires {
                if !taught.contains(&need.as_str()) {
                    problems.push(format!(
                        "{}: requires '{need}', which no entry teaches",
                        r.id
                    ));
                }
            }
        }
        problems
    }

    /// Entries placed in a curriculum system, ordered by stage as that
    /// system writes it.
    pub fn by_system(&self, system: &str) -> Vec<(&str, &Entry)> {
        let mut out: Vec<(&str, &Entry)> = self
            .reactions
            .iter()
            .filter_map(|r| {
                r.curriculum
                    .iter()
                    .find(|p| p.system == system)
                    .map(|p| (p.stage.as_str(), r))
            })
            .collect();
        out.sort_by_key(|(stage, _)| stage.to_string());
        out
    }

    /// Coverage: what the codex teaches, grouped so gaps are visible.
    pub fn coverage(&self) -> Coverage {
        let mut c = Coverage::default();
        for r in &self.reactions {
            for x in &r.concepts {
                push_unique(&mut c.concepts, x);
            }
            for x in &r.apparatus {
                push_unique(&mut c.apparatus, x);
            }
            for x in &r.calculations {
                push_unique(&mut c.calculations, x);
            }
            for x in &r.models {
                push_unique(&mut c.models, x);
            }
            for p in &r.curriculum {
                push_unique(&mut c.systems, &p.system);
            }
        }
        c
    }

    /// Every concept the codex teaches, with the entries that teach it.
    pub fn concept_index(&self) -> Vec<(String, Vec<String>)> {
        let mut index: std::collections::BTreeMap<String, Vec<String>> = Default::default();
        for r in &self.reactions {
            for c in &r.concepts {
                index.entry(c.clone()).or_default().push(r.id.clone());
            }
        }
        index.into_iter().collect()
    }
}

/// What the codex covers, for seeing what it does not.
#[derive(Debug, Default, Serialize, Deserialize)]
pub struct Coverage {
    pub concepts: Vec<String>,
    pub apparatus: Vec<String>,
    pub calculations: Vec<String>,
    pub models: Vec<String>,
    pub systems: Vec<String>,
}

fn push_unique(v: &mut Vec<String>, item: &str) {
    if !v.iter().any(|e| e == item) {
        v.push(item.to_string());
    }
}

/// Does an observed event match a claim like `precipitated:AgCl`?
pub fn event_matches(event: &kerotakis_core::Event, claim: &str) -> bool {
    use kerotakis_core::Event as E;
    let (kind, want) = match claim.split_once(':') {
        Some((k, s)) => (k, Some(s)),
        None => (claim, None),
    };
    let (actual_kind, actual_species): (&str, Option<&str>) = match event {
        E::Precipitated { species, .. } => ("precipitated", Some(species.0.as_str())),
        E::Dissolved { species, .. } => ("dissolved", Some(species.0.as_str())),
        E::GasEvolved { species, .. } => ("gas_evolved", Some(species.0.as_str())),
        E::Consumed { species, .. } => ("consumed", Some(species.0.as_str())),
        E::Added { species, .. } => ("added", Some(species.0.as_str())),
        E::FlameTest { species, .. } => ("flame_test", Some(species.0.as_str())),
        E::Ignited { .. } => ("ignited", None),
        E::DidNotIgnite { .. } => ("did_not_ignite", None),
        E::HazardWarning { .. } => ("hazard_warning", None),
        E::SafetyVeto { .. } => ("safety_veto", None),
        E::ReactionOccurred { .. } => ("reaction", None),
        E::SolutionCharacterized { .. } => ("solution", None),
        E::ThermalEquilibrium { .. } => ("thermal_equilibrium", None),
        E::TemperatureChanged { .. } => ("temperature_changed", None),
        E::Evaporated { .. } => ("evaporated", None),
        E::Filtered { .. } => ("filtered", None),
        E::Transferred { .. } => ("transferred", None),
        E::Measured { .. } => ("measured", None),
        E::Observed { .. } => ("observed", None),
        E::VesselCreated { .. } => ("vessel_created", None),
        E::NotYetModeled { .. } => ("not_yet_modelled", None),
        E::SolverFailed { .. } => ("solver_failed", None),
    };
    if actual_kind != kind {
        return false;
    }
    match (want, actual_species) {
        (None, _) => true,
        (Some(w), Some(a)) => w == a,
        (Some(_), None) => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = r#"
[[reaction]]
id = "test"
equation = "A + B → C"
concepts = ["thing"]

[reaction.setup]
script = "add v1 water 100mL"

[reaction.expect]
events = ["added:water"]

[reaction.registers]
lv1 = "c"
lv2 = "s"
lv3 = "e"

[reaction.provenance]
source = "textbook"
"#;

    #[test]
    fn parses_and_validates() {
        let codex = Codex::parse(SAMPLE).expect("parses");
        assert_eq!(codex.reactions.len(), 1);
        assert!(codex.structural_problems().is_empty());
        assert_eq!(codex.concept_index()[0].0, "thing");
    }

    #[test]
    fn catches_an_entry_that_claims_nothing() {
        let text = SAMPLE.replace("events = [\"added:water\"]", "events = []");
        let codex = Codex::parse(&text).expect("parses");
        let problems = codex.structural_problems();
        assert!(
            problems
                .iter()
                .any(|p| p.contains("claims nothing checkable")),
            "{problems:?}"
        );
    }

    #[test]
    fn catches_a_dangling_prerequisite() {
        let text = SAMPLE.replace(
            "concepts = [\"thing\"]",
            "concepts = [\"thing\"]\nrequires = [\"nowhere\"]",
        );
        let codex = Codex::parse(&text).expect("parses");
        assert!(codex
            .structural_problems()
            .iter()
            .any(|p| p.contains("which no entry teaches")));
    }
}
