//! CAP-21: generate the species registry from the compiled data pack.
//!
//! The registry used to be 1,400 lines of hand-written Rust literals,
//! which made every new species a code change and a release — the exact
//! ceiling ROADMAP names. The source of truth is now
//! `data/registry/registry-source-v1.json` (the DATA-002 export, kept
//! current by `kerotakis-registry-export`); this script joins its
//! normalized records back into `SpeciesData` literals at build time, so
//! the table stays `static`, keeps its `&'static str` fields, costs
//! nothing at runtime, and ships unchanged to wasm.
//!
//! Faithfulness is not assumed: `tests/registry_snapshot.rs` pins the
//! generated table — every field, every evaluated spectrum band — to a
//! golden captured from the hand-written table before the switch.

use std::fmt::Write as _;

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let src = std::path::Path::new(&manifest).join("../../data/registry/registry-source-v1.json");
    println!("cargo:rerun-if-changed={}", src.display());
    let text = std::fs::read_to_string(&src)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", src.display()));
    let doc: serde_json::Value = serde_json::from_str(&text).expect("registry JSON parses");

    let identities = doc["identities"].as_array().expect("identities");
    let compositions = doc["compositions"].as_array().expect("compositions");
    let thermo = doc["phase_thermodynamics"].as_array().expect("thermo");
    let optical = doc["optical"].as_array().expect("optical");
    let params = doc["model_parameters"].as_array().expect("params");
    let sources = doc["sources"].as_array().expect("sources");

    let find_source = |id: &str| -> &str {
        sources
            .iter()
            .find(|s| s["id"] == id)
            .and_then(|s| s["citation"].as_str())
            .unwrap_or_else(|| panic!("no source citation for {id}"))
    };
    let composition_for = |key: &str| -> &serde_json::Value {
        compositions
            .iter()
            .find(|c| c["species_id"] == key)
            .unwrap_or_else(|| panic!("no composition for {key}"))
    };
    let thermo_for = |key: &str, prop: &str| -> Option<&serde_json::Value> {
        thermo
            .iter()
            .find(|t| t["species_id"] == key && t["property"] == prop)
    };
    let optical_for = |key: &str| -> Option<&serde_json::Value> {
        optical.iter().find(|o| o["species_id"] == key)
    };
    let param_for = |key: &str, parameter: &str| -> Option<f64> {
        params
            .iter()
            .find(|p| {
                p["parameter"] == parameter
                    && p["subject"]["kind"] == "species"
                    && p["subject"]["id"] == key
            })
            .and_then(|p| p["quantity"]["value"].as_f64())
    };

    let phase_variant = |p: &str| -> &'static str {
        match p {
            "solid" => "Phase::Solid",
            "liquid" => "Phase::Liquid",
            "aqueous" => "Phase::Aqueous",
            "gas" => "Phase::Gas",
            other => panic!("phase '{other}' has no runtime Phase variant"),
        }
    };
    let str_opt = |v: &serde_json::Value| -> String {
        match v.as_str() {
            Some(s) => format!("Some({s:?})"),
            None => "None".to_string(),
        }
    };
    let f64_lit = |v: f64| -> String {
        // `{:?}` prints the shortest representation that round-trips.
        format!("{v:?}")
    };

    let mut out = String::new();
    writeln!(
        out,
        "// Generated by build.rs from data/registry/registry-source-v1.json — do not edit.\n\
         pub static REGISTRY: &[SpeciesData] = &["
    )
    .unwrap();

    for identity in identities {
        let key = identity["id"].as_str().expect("identity id");
        let comp = composition_for(key);
        let mm = thermo_for(key, "molar_mass").unwrap_or_else(|| panic!("no molar mass for {key}"));
        let molar_mass = mm["quantity"]["value"].as_f64().unwrap();
        let standard_phase = phase_variant(mm["phase"].as_str().unwrap());
        let heat_capacity = thermo_for(key, "molar_heat_capacity")
            .and_then(|t| t["quantity"]["value"].as_f64())
            .unwrap_or_else(|| panic!("no heat capacity for {key}"));
        let density = thermo_for(key, "mass_density")
            .and_then(|t| t["quantity"]["value"].as_f64())
            .unwrap_or_else(|| panic!("no density for {key}"));
        let dissolution = thermo_for(key, "enthalpy_of_dissolution")
            .and_then(|t| t["quantity"]["value"].as_f64());

        let opt = optical_for(key);
        let appearance = opt.map_or("None".into(), |o| str_opt(&o["appearance"]));
        let flame = opt.map_or("None".into(), |o| str_opt(&o["flame_colour"]));
        let colour = match opt.and_then(|o| o["reflective_srgb"].as_str()) {
            Some(hex) => {
                let h = hex.trim_start_matches('#');
                let r = u8::from_str_radix(&h[0..2], 16).unwrap();
                let g = u8::from_str_radix(&h[2..4], 16).unwrap();
                let b = u8::from_str_radix(&h[4..6], 16).unwrap();
                let strength = param_for(key, "strength")
                    .unwrap_or_else(|| panic!("srgb without tint strength for {key}"));
                format!(
                    "Some(Colour {{ r: {r}, g: {g}, b: {b}, strength: {} }})",
                    f64_lit(strength)
                )
            }
            None => "None".to_string(),
        };
        let spectrum = match opt
            .and_then(|o| o["spectrum"].as_array())
            .filter(|s| !s.is_empty())
        {
            Some(samples) => {
                assert_eq!(samples.len(), 16, "{key}: spectrum must carry 16 bands");
                let bands: Vec<String> = samples
                    .iter()
                    .map(|s| f64_lit(s["molar_absorptivity"]["value"].as_f64().unwrap()))
                    .collect();
                format!("Some(|| [{}])", bands.join(", "))
            }
            None => "None".to_string(),
        };

        let dws = param_for(key, "dissolves-without-speciation").unwrap_or(0.0) != 0.0;
        let foa = param_for(key, "forms-only-above")
            .map_or("None".to_string(), |v| format!("Some({})", f64_lit(v)));
        let provenance = find_source(
            identity["evidence"]["source_id"]
                .as_str()
                .expect("source id"),
        );

        writeln!(
            out,
            "    SpeciesData {{\n        key: {key:?},\n        name: {:?},\n        formula: {:?},\n        inchikey: {:?},\n        molar_mass: {},\n        heat_capacity: {},\n        density: {},\n        standard_phase: {standard_phase},\n        appearance: {appearance},\n        flame_colour: {flame},\n        colour: {colour},\n        spectrum: {spectrum},\n        dissolution_enthalpy_kj: {},\n        dissolves_without_speciation: {dws},\n        forms_only_above_k: {foa},\n        provenance: {provenance:?},\n    }},",
            identity["name"].as_str().expect("name"),
            comp["formula"].as_str().expect("formula"),
            // identifiers.inchikey, not canonical_key: the pack synthesizes
            // a legacy: placeholder key for species that have no InChIKey
            // (enzymes, exotic ions), and the runtime field means the real
            // identifier or nothing.
            identity["identifiers"]["inchikey"].as_str().unwrap_or(""),
            f64_lit(molar_mass),
            f64_lit(heat_capacity),
            f64_lit(density),
            dissolution.map_or("None".to_string(), |v| format!("Some({})", f64_lit(v))),
        )
        .unwrap();
    }
    writeln!(out, "];").unwrap();

    let dest =
        std::path::Path::new(&std::env::var("OUT_DIR").unwrap()).join("species_generated.rs");
    std::fs::write(dest, out).unwrap();
}
