#!/usr/bin/env python3
"""Extract the chemistry topic spine from the openeduhub OEH vocabulary.

`oehTopics.ttl` is the "Taxonomie von Lehrplanthemen in WirLernenOnline" —
a SKOS hierarchy of German curriculum topics, published under **CC0 1.0**
(verified: the repository LICENSE is CC0 1.0 Universal). That makes it the
one topic vocabulary in this space we can use without conditions, and it is
in German, which matters for the first market.

What it gives us: ~195 chemistry topics, hierarchical, each with a German
label and usually a definition. What it does *not* give us: any mapping to
school years — that axis has to come from curricula that are themselves
free (Norway's Grep API and Austria's RIS are public domain and
API-served), or be built ourselves.

    usage: extract-oeh-topics.py oehTopics.ttl > codex/concepts.toml

Source: https://github.com/openeduhub/oeh-metadata-vocabs
"""

import re
import sys
import unicodedata

CHEMIE_DISCIPLINE = "discipline/100"
SOURCE = "oehTopics (openeduhub / WirLernenOnline), CC0 1.0"


def slug(label):
    """A stable ascii slug: ä→ae and friends, because German labels are
    the primary key here and umlauts in identifiers age badly."""
    s = label.lower()
    for a, b in [("ä", "ae"), ("ö", "oe"), ("ü", "ue"), ("ß", "ss")]:
        s = s.replace(a, b)
    s = unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode()
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    return s


def field(block, pattern):
    m = re.search(pattern, block)
    return m.group(1) if m else None


def main(path):
    text = open(path, encoding="utf-8").read()
    blocks = [b for b in text.split("\n\n") if b.strip().startswith("<")]

    # Pass 1: every concept, so `broader` can be resolved to a label.
    labels = {}
    for b in blocks:
        uid = field(b, r"^<([0-9a-f-]{36})>")
        label = field(b, r'skos:prefLabel "([^"]+)"@de')
        if uid and label:
            labels[uid] = label

    # Pass 2: the chemistry ones.
    out = []
    for b in blocks:
        if CHEMIE_DISCIPLINE not in b:
            continue
        uid = field(b, r"^<([0-9a-f-]{36})>")
        label = field(b, r'skos:prefLabel "([^"]+)"@de')
        if not uid or not label:
            continue
        definition = field(b, r'skos:definition "([^"]*)"@de')
        broader_uid = field(b, r"skos:broader <([0-9a-f-]{36})>")
        broader = labels.get(broader_uid) if broader_uid else None
        out.append(
            {
                "id": slug(label),
                "label_de": label,
                "definition_de": definition,
                "broader": slug(broader) if broader else None,
                "oeh": uid,
            }
        )

    out.sort(key=lambda c: c["id"])
    seen = set()
    print("# Chemistry topic spine, extracted from the OEH vocabulary.")
    print("#")
    print("# GENERATED by tools/extract-oeh-topics.py — do not edit by hand.")
    print(f"# Source: {SOURCE}")
    print("#")
    print("# These are *topics*, not a curriculum: the vocabulary carries no")
    print("# year mapping. Placing a topic in a school year is a separate")
    print("# claim, made per curriculum in the codex entries themselves.")
    print()
    for c in out:
        if c["id"] in seen or not c["id"]:
            continue
        seen.add(c["id"])
        print("[[concept]]")
        print(f'id = "{c["id"]}"')
        print(f'label_de = {toml_str(c["label_de"])}')
        if c["definition_de"]:
            print(f'definition_de = {toml_str(c["definition_de"])}')
        if c["broader"]:
            print(f'broader = "{c["broader"]}"')
        print(f'oeh = "{c["oeh"]}"')
        print(f'source = "{SOURCE}"')
        print()
    print(f"# {len(seen)} concepts", file=sys.stderr)


def toml_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
