#!/usr/bin/env python3
"""CAP-19: generate differential-oracle fixtures from the Python `thermo`
package (MIT, Caleb Bell) — the build-time second opinion PLAN.md assigns
to kerotakis-thermo.

Two fixture families, both replayed by tests/thermo_oracle.rs:

  gamma  x t_kelvin ge gw
      thermo's own UNIFAC (original published interaction parameters)
      for the ethanol-water binary. Same parameters, independent
      implementation: this is the check that would have caught the
      combinatorial double-division bug on day one.

  bubble x p_kpa t_celsius y_ethanol
      bubble points solved HERE, in this script, by plain bisection on
      sum(x_i * gamma_i(T) * Psat_i(T)) = P, with gammas from thermo and
      the same Antoine constants vle.rs curates (duplicated on purpose:
      the oracle solves the same stated model independently; if the
      constants drift apart the fixtures stop matching and say so).

Run from the repo root with a venv holding `thermo`:
  ./path/to/python tools/gen-thermo-fixtures.py \
      > crates/kerotakis-thermo/tests/fixtures/thermo_oracle.tsv
"""

from thermo.unifac import UNIFAC, UFIP, UFSG

ETHANOL_GROUPS = {1: 1, 2: 1, 14: 1}  # CH3 CH2 OH
WATER_GROUPS = {16: 1}  # H2O

# Antoine, log10(P/kPa) = a - b/(T_C + c) — must match vle.rs (cited there:
# Stull 1947 fits, mmHg-converted).
ANTOINE = {
    "ethanol": (7.32907, 1642.89, 230.300),
    "water": (7.19621, 1730.63, 233.426),
}
ATM = 101.325


def gammas(x, t_k):
    ge = UNIFAC.from_subgroups(
        T=t_k,
        xs=[x, 1.0 - x],
        chemgroups=[ETHANOL_GROUPS, WATER_GROUPS],
        interaction_data=UFIP,
        subgroups=UFSG,
    )
    return ge.gammas()


def psat(name, t_c):
    a, b, c = ANTOINE[name]
    return 10.0 ** (a - b / (t_c + c))


def bubble(x, p_kpa):
    def total(t_c):
        g = gammas(x, t_c + 273.15)
        return x * g[0] * psat("ethanol", t_c) + (1.0 - x) * g[1] * psat("water", t_c) - p_kpa

    lo, hi = 0.0, 200.0
    for _ in range(200):
        mid = 0.5 * (lo + hi)
        if total(mid) < 0.0:
            lo = mid
        else:
            hi = mid
    t = 0.5 * (lo + hi)
    g = gammas(x, t + 273.15)
    pe = x * g[0] * psat("ethanol", t)
    pw = (1.0 - x) * g[1] * psat("water", t)
    return t, pe / (pe + pw)


def main():
    print("# generated by tools/gen-thermo-fixtures.py — do not edit")
    import thermo

    print(f"# thermo {thermo.__version__}, UNIFAC original parameters (UFIP/UFSG)")
    for x in [0.01, 0.05, 0.1, 0.2, 0.3, 0.5, 0.7, 0.894, 0.99]:
        for t_k in [298.15, 325.0, 351.0, 360.0]:
            ge, gw = gammas(x, t_k)
            print(f"gamma\t{x}\t{t_k}\t{ge:.10f}\t{gw:.10f}")
    for x in [0.01, 0.05, 0.1, 0.3, 0.5, 0.7, 0.894]:
        t, y = bubble(x, ATM)
        print(f"bubble\t{x}\t{ATM}\t{t:.6f}\t{y:.8f}")


if __name__ == "__main__":
    main()
