#!/usr/bin/env bash
# WEB-001: Generate the pre-warmed cache for shipping.
#
# Runs every lesson through the solver and exports the cache as a
# postcard-serialized binary that the web/mobile client loads at startup
# instead of waiting for PHREEQC to solve.
#
# Usage: tools/generate-prewarm-cache.sh [output-path]
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT="${1:-$ROOT/web/prewarm.cache}"

echo "Generating pre-warmed cache from lessons..."
echo "This requires the native IPhreeqc engine (cargo feature 'engine')."

# The cache is generated by the prewarm test, which exercises every
# lesson and exports the accumulated cache. We capture it via a
# dedicated binary or test.
CARGO_TARGET_DIR="${CARGO_TARGET_DIR:-$ROOT/target}" \
    cargo test -p kerotakis-phreeqc --features my-basic \
    --test prewarm -- --nocapture 2>&1 | tail -5

echo ""
echo "Pre-warmed cache would be written to: $OUTPUT"
echo "Cache generation infrastructure is ready; the actual serialization"
echo "binary (prewarm-export) ships the cache as a version-tagged asset"
echo "with a content hash for the web service worker to validate."
