#!/usr/bin/env python3
"""Golden-fixture generator for kerotakis-thermo (P3p), from the Python
`thermo` oracle.

PLAN.md names this exact pattern ("Golden fixtures generated by build-time
`thermo`"): a mature independent implementation computes reference VLE
results once, the numbers are checked in as fixtures, and the Rust crate's
tests diff against them. The oracle is **not** part of the build, by
design — no import from the crates, nothing from here vendored, same
stance as kinetics-oracle.py.

Method, stated so the comparison is apples-to-apples:
  - Activity coefficients: original UNIFAC (version=0) with the UFSG/UFIP
    subgroup and interaction tables as shipped in `thermo` — these derive
    from the original open-literature parameter publications, which is the
    same corpus kerotakis-thermo's own UNIFAC must curate from. Groups:
    water = {H2O}, ethanol = {CH3, CH2, OH}.
  - Pure vapour pressures: `thermo.VaporPressure`'s default correlation
    per compound; the chosen method string is recorded per compound in
    the fixture, because "the oracle said so" is not provenance.
  - Bubble points: modified Raoult, P = Σ x_i γ_i(x,T) Psat_i(T), solved
    for T by bisection. Ideal vapour phase — at 1 atm that is the same
    approximation every school treatment makes, and the fixture says so.

The acceptance target this feeds (PLAN P3p): the ethanol-water azeotrope
near x_EtOH ≈ 0.89-0.90 mol (95.6% by mass), T ≈ 78.1-78.2 °C at 1 atm.
The script checks its own output against that window and refuses to write
a fixture that misses it — an oracle that cannot reproduce the textbook
azeotrope has no business anchoring anyone's tests.

    python3 -m venv .venv && .venv/bin/pip install thermo
    .venv/bin/python tools/vle-oracle.py > tools/fixtures/vle-ethanol-water.json
"""

import json
import sys

import thermo
from thermo import VaporPressure
from thermo.unifac import UFIP, UFSG, UNIFAC

P_ATM = 101325.0

# UNIFAC subgroup assignments (original UNIFAC numbering: 1=CH3, 2=CH2,
# 14=OH, 16=H2O).
GROUPS = {
    "water": {16: 1},
    "ethanol": {1: 1, 2: 1, 14: 1},
}
NAMES = ["ethanol", "water"]  # component order everywhere below
MW = {"ethanol": 46.06844, "water": 18.01528}

psats = {
    "ethanol": VaporPressure(CASRN="64-17-5"),
    "water": VaporPressure(CASRN="7732-18-5"),
}


def gammas(x_ethanol: float, T: float):
    xs = [x_ethanol, 1.0 - x_ethanol]
    model = UNIFAC.from_subgroups(
        T=T,
        xs=xs,
        chemgroups=[GROUPS["ethanol"], GROUPS["water"]],
        version=0,
        interaction_data=UFIP,
        subgroups=UFSG,
    )
    return model.gammas()


def bubble_T(x_ethanol: float, P: float = P_ATM):
    """Modified-Raoult bubble point by bisection; returns (T, y_ethanol)."""
    xs = [x_ethanol, 1.0 - x_ethanol]

    def resid(T: float) -> float:
        g = gammas(x_ethanol, T) if 0.0 < x_ethanol < 1.0 else [1.0, 1.0]
        return sum(
            x * gi * psats[n](T) for x, gi, n in zip(xs, g, NAMES)
        ) - P

    lo, hi = 300.0, 400.0
    assert resid(lo) < 0.0 < resid(hi), "bracket failed"
    for _ in range(80):
        mid = 0.5 * (lo + hi)
        if resid(mid) < 0.0:
            lo = mid
        else:
            hi = mid
    T = 0.5 * (lo + hi)
    g = gammas(x_ethanol, T) if 0.0 < x_ethanol < 1.0 else [1.0, 1.0]
    y_eth = x_ethanol * g[0] * psats["ethanol"](T) / P
    return T, y_eth


def main() -> int:
    fixture = {
        "_provenance": {
            "generator": "tools/vle-oracle.py",
            "oracle": f"thermo {thermo.__version__} (MIT; build-time oracle only, never shipped)",
            "activity_model": "original UNIFAC (version=0), UFSG/UFIP tables as shipped in thermo, derived from the original open-literature parameter publications",
            "vapor_pressure_methods": {
                n: psats[n].method for n in NAMES
            },
            "phase_model": "modified Raoult, ideal vapour, P = 101325 Pa",
            "note": "reference values for kerotakis-thermo golden tests; regenerate only deliberately and re-read every consumer when the numbers move",
        },
        "pure": {},
        "unifac_gammas": [],
        "txy_1atm": [],
        "azeotrope_1atm": None,
    }

    # Pure-component anchors: normal boiling points and a few Psat values.
    for n in NAMES:
        Tb, _ = bubble_T(1.0 if n == "ethanol" else 0.0)
        fixture["pure"][n] = {
            "normal_boiling_point_K": round(Tb, 3),
            "psat_Pa": {
                str(T): round(psats[n](T), 1) for T in (298.15, 323.15, 351.45, 373.15)
            },
        }

    # Direct diff targets for the Rust UNIFAC: gammas on a grid.
    for T in (298.15, 351.15):
        for x in (0.05, 0.25, 0.5, 0.75, 0.95):
            g = gammas(x, T)
            fixture["unifac_gammas"].append(
                {
                    "T_K": T,
                    "x_ethanol": x,
                    "gamma_ethanol": round(g[0], 6),
                    "gamma_water": round(g[1], 6),
                }
            )

    # The Txy curve at 1 atm, and the azeotrope by bisection on y - x.
    for x in (0.0, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.85, 0.9, 0.95, 1.0):
        T, y = bubble_T(x)
        fixture["txy_1atm"].append(
            {"x_ethanol": x, "T_K": round(T, 3), "y_ethanol": round(y, 5)}
        )

    lo, hi = 0.8, 0.999  # y > x below the azeotrope, y < x above it
    assert bubble_T(lo)[1] > lo and bubble_T(hi)[1] < hi
    for _ in range(60):
        mid = 0.5 * (lo + hi)
        if bubble_T(mid)[1] > mid:
            lo = mid
        else:
            hi = mid
    x_az = 0.5 * (lo + hi)
    T_az, _ = bubble_T(x_az)
    w_az = x_az * MW["ethanol"] / (x_az * MW["ethanol"] + (1 - x_az) * MW["water"])
    fixture["azeotrope_1atm"] = {
        "x_ethanol": round(x_az, 5),
        "mass_fraction_ethanol": round(w_az, 5),
        "T_K": round(T_az, 3),
    }

    # The oracle audits itself against the textbook before it is allowed
    # to anchor anyone else's tests.
    ok = 0.88 <= x_az <= 0.92 and 350.6 <= T_az <= 352.0
    if not ok:
        print(
            f"REFUSING to write fixture: azeotrope x={x_az:.4f}, T={T_az:.2f} K "
            "misses the textbook window (x 0.88-0.92, T 350.6-352.0 K)",
            file=sys.stderr,
        )
        return 1

    json.dump(fixture, sys.stdout, indent=1)
    print()
    print(
        f"oracle self-check ok: azeotrope x_EtOH={x_az:.4f} "
        f"({100*w_az:.1f} wt%), T={T_az-273.15:.2f} °C",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
